version: '3.8'

services:
  aurel-ai-server:
    build:
      context: .
      dockerfile: apps/aurel-ai-server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/aurel_ai_db
    depends_on:
      - mongo

  aurel-ai:
    build:
      context: .
      dockerfile: apps/aurel-ai/Dockerfile
    ports:
      - "4200:4200"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword